# Generated by Django 5.2.10 on 2026-01-26 08:47

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='导语')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('job_title', models.CharField(max_length=255, verbose_name='职位名称')),
                ('location', models.CharField(max_length=100, verbose_name='工作地点')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='薪资范围')),
                ('description', wagtail.fields.RichTextField(verbose_name='职位描述')),
                ('job_type', models.CharField(choices=[('intern', '实习'), ('fulltime', '全职'), ('parttime', '兼职')], default='fulltime', max_length=20, verbose_name='职位类型')),
                ('source_website', models.CharField(default='智联招聘', max_length=50, verbose_name='来源网站')),
                ('source_url', models.URLField(blank=True, verbose_name='原始链接')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, help_text='可选，用于身份验证', max_length=20, verbose_name='学号')),
                ('school', models.CharField(choices=[('tsinghua', '清华大学'), ('pku', '北京大学'), ('fudan', '复旦大学'), ('sjtu', '上海交通大学'), ('zju', '浙江大学'), ('other', '其他院校')], default='other', max_length=50, verbose_name='学校')),
                ('major', models.CharField(choices=[('cs', '计算机科学'), ('se', '软件工程'), ('ee', '电子信息'), ('business', '工商管理'), ('finance', '金融学'), ('design', '设计艺术'), ('other', '其他专业')], default='other', max_length=50, verbose_name='专业')),
                ('graduation_year', models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], default=2025, verbose_name='毕业年份')),
                ('preferred_job_types', models.CharField(default='intern,fulltime', help_text='逗号分隔：intern(实习),fulltime(全职),parttime(兼职)', max_length=100, verbose_name='偏好职位类型')),
                ('preferred_locations', models.CharField(default='北京,上海,深圳', help_text='逗号分隔的城市名', max_length=200, verbose_name='偏好工作地点')),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/%Y/%m/', verbose_name='简历')),
                ('resume_text', models.TextField(blank=True, help_text='用于搜索匹配的简历文本', verbose_name='简历文本内容')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已验证学生身份')),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后活跃时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
                'ordering': ['-created_at'],
            },
        ),
    ]
