# Generated by Django 5.2.10 on 2026-01-27 03:23

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', '已收藏'), ('applied', '已申请'), ('viewed', '已查看'), ('contacted', '已联系'), ('rejected', '已拒绝'), ('accepted', '已接受')], default='saved', max_length=20, verbose_name='申请状态')),
                ('applied_date', models.DateTimeField(blank=True, null=True, verbose_name='申请时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('source', models.CharField(default='website', max_length=50, verbose_name='来源')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '职位申请',
                'verbose_name_plural': '职位申请',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'job_page')},
            },
        ),
    ]
