# Generated by Django 5.2.10 on 2026-01-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_recommendationspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobindexpage',
            options={'verbose_name': '职位索引页面', 'verbose_name_plural': '职位索引页面'},
        ),
        migrations.AlterModelOptions(
            name='jobpage',
            options={'verbose_name': '职位页面', 'verbose_name_plural': '职位页面'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='手机号码', max_length=20, verbose_name='联系电话'),
        ),
    ]
