# Generated by Django 5.2.10 on 2026-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobindexpage_options_alter_jobpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像图片', null=True, upload_to='student_avatars/%Y/%m/', verbose_name='头像'),
        ),
    ]
