# Generated by Django 5.2.10 on 2026-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_studentprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='ai_report',
            field=models.TextField(blank=True, help_text='AI生成的职场竞争力分析报告', verbose_name='AI分析报告'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ai_report_updated_at',
            field=models.DateTimeField(blank=True, help_text='AI分析报告的最后更新时间', null=True, verbose_name='AI报告更新时间'),
        ),
    ]
