# Generated by Django 5.2.10 on 2026-02-10 16:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_studentprofile_ai_extracted_fields'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='显示在简历列表上方的介绍文字', verbose_name='页面介绍')),
            ],
            options={
                'verbose_name': '简历索引页面',
                'verbose_name_plural': '简历索引页面',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('user_id', models.IntegerField(help_text='关联的用户ID', verbose_name='用户ID')),
                ('student_name', models.CharField(blank=True, max_length=100, verbose_name='学生姓名')),
                ('student_email', models.EmailField(blank=True, max_length=254, verbose_name='学生邮箱')),
                ('resume_text', models.TextField(blank=True, help_text='从简历中提取的文本内容', verbose_name='简历文本内容')),
                ('ai_extracted_school', models.CharField(blank=True, max_length=200, verbose_name='AI提取的学校')),
                ('ai_extracted_major', models.CharField(blank=True, max_length=200, verbose_name='AI提取的专业')),
                ('ai_extracted_skills', models.JSONField(blank=True, default=list, verbose_name='AI提取的核心技能')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('resume_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='简历文件')),
            ],
            options={
                'verbose_name': '简历页面',
                'verbose_name_plural': '简历页面',
            },
            bases=('wagtailcore.page',),
        ),
    ]
