# Generated by Django 5.2.10 on 2026-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobapplication_split_save_and_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投递时间'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('applied', '已投递'), ('contacted', '已联系'), ('rejected', '已拒绝'), ('accepted', '已接受')], default='', help_text='仅在已投递后表示跟进状态；未投递时留空', max_length=20, verbose_name='投递进度'),
        ),
    ]
